# Generated by Django 3.0.7 on 2020-09-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerRegistrationModel')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.FoodItemsModel')),
            ],
        ),
    ]
