# Generated by Django 3.0.7 on 2020-09-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200930_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='items',
            new_name='c_id',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='status',
        ),
    ]
